name: pdfscraper_py

on: push

# or set timer (runs at 17:25 utc)
#on:
#  schedule:
#  - cron: 25 17 * * *

jobs:
  get-data-from-pdf:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Download file
        # run: wget https://github.com/jlomako/download-file-to-repository/raw/main/data/urgence.pdf
        run: wget https://www.msss.gouv.qc.ca/professionnels/statistiques/documents/urgences/Rap_Quotid_SituatUrgence1.pdf
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      - name: Run script
        run: python extract_pdf.py
        
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "Scheduled Github Action on $(date)"
          git push origin main
